title: Issues with GitHub Pages Project 
author: GitHub Pages User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  When I first started working on the GitHub Pages project, the minima theme,
  or any changes saved in the _config.yml file would not load. I deleted the
  respiratory and I'm starting from scratch. Let's see how it works now.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
